HOST = "224.1.1.1"
PORT_BASE = 254
PORT_INITIAL = PORT_BASE + 1
PORT_CLIENT_BASE = PORT_INITIAL + 1

INDEX_ADDR_HOST = 0
INDEX_ADDR_PORT = 1

SAMPLE_256_BYTES = bytes([x for x in range(256)])

ASCII_DATA_REQUEST_SEND = 1
ASCII_ACK = 6

SERIAL_BAUD = 9600
SERIAL_TIMEOUT = 1